### ISSUE TITLE
Médias perdus - incomplets / Connexion qui saute ? autre logique ?

### ISSUE THREAD

**Issue by Gremgrem** [l-atelier-des-chercheurs/PLATEAU#13]

**Comment by paulinegourlet** [comment]
Je te mets ici l'exemple d'enregistrements sonores (il faut regarder les timestamps, je ne comprends pas la logique, elle ne se répète pas d'une fois sur l'autre) :
 
<img width="825" alt="Screenshot 2020-10-28 at 08 14 21" src="https://user-images.githubusercontent.com/7995654/97404051-c5d42180-18f5-11eb-9f62-bc379f7e5454.png">


<img width="552" alt="Screenshot 2020-10-28 at 08 14 07" src="https://user-images.githubusercontent.com/7995654/97404047-c40a5e00-18f5-11eb-8bfd-1a511f42aebb.png">
Ici par exemple, c'est vraiment bizarre : le premier média fait 5 sec., le suivant 2 min, celui d'après aussi et les autres sont vides. Mais ils ont tous le même timestamp.

L'enregistrement, c'était sur mon tel -> chrome / android - 4G

**Comment by paulinegourlet** [comment]
Ajouter un message dans le panneau capture -> 
"attention si vous êtes sur un téléphone, privilégier l'enregistrement natif et importer" (à reformuler !)

**Comment by louis-ev** [comment]
Le timestamp affiché c’est la date de création du fichier et pas d’upload — utile en cas d’importation des contenus après coup pour qu’ils soient bien rangés. Peut-être qu’il faudrait pouvoir changer ça cela dit… Dans tous les cas afficher la durée sur la vignette devrait être utile + avoir une légende.
Je ne sais pas trop d’où pourraient venir ces bugs par contre… Tu pourrais trouver une manière de les reproduire sur ordinateur ?
