### ISSUE TITLE
RESPONSIVE (page d'accueil + wrap du menu des panneaux sous le titre + meilleure vue capture + gestion esclave)

### ISSUE THREAD

**Issue by Gremgrem** [l-atelier-des-chercheurs/PLATEAU#15]

**Comment by paulinegourlet** [comment]
![Uploading Screenshot_20201020_165910_com.android.chrome.jpg…]()
![Uploading Screenshot_20201020_165852_com.android.chrome.jpg…]()

**Comment by paulinegourlet** [comment]
![Screenshot_20201020_165910_com android chrome](https://user-images.githubusercontent.com/7995654/96604939-f1537c80-12f5-11eb-9a95-4de290e4d484.jpg)

**Comment by paulinegourlet** [comment]
![Uploading Screenshot_20201020_165852_com.android.chrome.jpg…]()

**Comment by paulinegourlet** [comment]
![Screenshot_20201020_165852_com android chrome](https://user-images.githubusercontent.com/7995654/96605047-0c25f100-12f6-11eb-958e-20398d94dc8f.jpg)

**Comment by paulinegourlet** [comment]
<img width="412" alt="Screenshot 2020-10-20 at 19 43 43" src="https://user-images.githubusercontent.com/7995654/96624390-f53ec900-130c-11eb-9f17-3f85f5e4b8e6.png">
<img width="1792" alt="Screenshot 2020-10-20 at 19 45 18" src="https://user-images.githubusercontent.com/7995654/96624393-f5d75f80-130c-11eb-8986-fbab67964ee4.png">

Gestion du mode "esclave" -> sur téléphone, le mode compo est problématique parce qu'on peut pas redimensionner à la taille de l'écran du tel (je comprends pas comment il détermine quelle taille fait la compo d'ailleurs ?)

**Comment by louis-ev** [comment]
C’est un peu fourre-tout cette issue…

- pouvoir zoomer/naviguer dans le panneau composition
- panneau édition en mode édition + pratique

**Comment by paulinegourlet** [comment]
Pour le panneau "compo" c'est peut-être pas la priorité en termes de responsive si on revoit la fonctionnalité.
Mais les autres pb de responsive sont importants : 
1)bandeau du haut à faire passer sur deux lignes max, 
2) gestion du pad sur tel (clavier + panneau planning en conflit avec le pad à l'endroit où on est en train d'écrire -> peut-être quand on a le curseur actif et la clavier, on ne voit que le pad et il faut une flèche pour retourner en arrière ?).

**Comment by paulinegourlet** [comment]
Page d'accueil -> gérer le responsive

**Comment by paulinegourlet** [comment]
URGENT : Pour la page d'accueil (surtout revoir l'affichage pour l'identification)

![screenshot-20210116-121959-com-android-chrome](https://user-images.githubusercontent.com/7995654/104810749-0b1e3600-57f7-11eb-8b19-e11d82d5d5cf.jpg)

**Comment by aurelient** [comment]
reformulée en 4 issues séparées
