### ISSUE TITLE
Export planning (HTML)

### ISSUE THREAD

**Issue by Gremgrem** [l-atelier-des-chercheurs/PLATEAU#23]

**Comment by louis-ev** [comment]
C’est opéraionnel :

![image](https://user-images.githubusercontent.com/1948417/75806780-9aa82b00-5d84-11ea-8380-1198761e4db4.png)

![image](https://user-images.githubusercontent.com/1948417/75806786-9c71ee80-5d84-11ea-98c0-5653e4deec84.png)
