### ISSUE TITLE
Changer couleur ou surligner "boutons" fenêtre photo

### ISSUE THREAD

**Issue by Gremgrem** [l-atelier-des-chercheurs/PLATEAU#35]
Pour le moment écriture noire sur photo noires: illisible 
![Screen Shot 2020-02-24 at 09 46 51](https://user-images.githubusercontent.com/54623918/75139576-46021180-56ed-11ea-8fee-2d3cf62001e6.png)

**Comment by louis-ev** [comment]
![image](https://user-images.githubusercontent.com/1948417/75800099-54999a00-5d79-11ea-8158-64c91ef21724.png)
