### ISSUE TITLE
Ajouter une marge quand on arrive au bout des notes

### ISSUE THREAD

**Issue by Gremgrem** [l-atelier-des-chercheurs/PLATEAU#39]
![Screen Shot 2020-03-03 at 14 37 43](https://user-images.githubusercontent.com/54623918/75781000-ad0e6e80-5d5c-11ea-8113-6469f55c696e.png)
![Screen Shot 2020-03-03 at 14 38 27](https://user-images.githubusercontent.com/54623918/75781002-ae3f9b80-5d5c-11ea-9dfe-eda300d378aa.png)

**Comment by louis-ev** [comment]
Je n’arrive pas à reproduire ce bug… tu peux me dire dans quel projet tu fais le test ?

**Comment by Gremgrem** [comment]
https://plateau.latelier-des-chercheurs.fr/celia-plateau-physique
Note "pince table - trépied octopus"
