### ISSUE TITLE
Organiser Projet sur la page d'accueil & Archiver une activité

### ISSUE THREAD

**Issue by aurelient** [l-atelier-des-chercheurs/PLATEAU#46]
Pourvoir archiver un activité, en gros simplement la mettre dans une autre catégorie, qui apparaitra en bas de la page d'accueil.

**Comment by louis-ev** [comment]
Yes.
Et la rendre "lecture-seule" ? ou non ?

**Comment by aurelient** [comment]
Il faut pas s'embêter pour le moment, c'est juste pour l'enlever de la liste principale

**Comment by paulinegourlet** [comment]
Comment on organise les projets sur la page d'accueil quand il commence à y en avoir bcp ?
(idem pour les "pads" planning -> s'est posé pour le workshop documentation quand chaque étudiant veut faire son pad ou son projet)
