### ISSUE TITLE
Est-ce que le nom "planning" est pertinent ? 

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/PLATEAU#57]
On dirait plutôt des "pads" / des prises de "notes".
Je le comprends bien dans le contexte des ateliers, mais est-ce qu'on peut trouver un terme qui s'adapte à d'autres contextes également ?

**Comment by louis-ev** [comment]
Oui, je suis d’accord. Phases ? Étapes ?

**Comment by paulinegourlet** [comment]
on je pensais plutôt à quelque chose de plus générique -> le côté séquencé est très intéressant dans le cadre d'atelier mais je vois que le côté pad souple  est aussi très apprécié. Du coup, peut-être un terme qui permette/implique les deux usages ?
ex :
-> "Description" / ""
-> "Bloc-notes" ou "Notes"
-> "Journal" (peut-être le mieux parce que ça comprend le côté "rendre compte d'un évènement" mais c'est pas très précis, donc ça sous entend le côté article écrit / compte rendu)

**Comment by louis-ev** [comment]
Effectivement, un terme neutre comme ceux là évitera les confusions (et ne gêne pas l’utilisation en atelier ou en distanciel).
@aurelient , qu’en penses-tu ?

**Comment by aurelient** [comment]
Je trouve "Journal" pas si mal, sinon Notes qui permet de rester super générique. Ou Cahier ?
