### ISSUE TITLE
[AFFICHAGE] Panneau planning trop important lorsque "pad" ouvert (surtout si petite largeur d'écran)

### ISSUE THREAD

**Issue by paulinegourlet** [l-atelier-des-chercheurs/PLATEAU#59]
<img width="841" alt="Screenshot 2020-10-28 at 08 19 33" src="https://user-images.githubusercontent.com/7995654/97404483-7a6e4300-18f6-11eb-87a8-0c068a469aaf.png">

**Comment by paulinegourlet** [comment]
C'est encore plus problématique sur téléphone (voir mon issue sur le responsive) -> trouver une astuce pour basculer en mode plein écran pad si largeur < X px (500 ?).

**Comment by paulinegourlet** [comment]
D'ailleurs, à l'usage, une flèche à gauche du titre du pad serait bienvenue pour retourner à la liste / replier le pad, quelle que soit la largeur de l'écran.

**Comment by louis-ev** [comment]
Le fait de garder la liste afficher, c’était pour permettre de savoir où tu en étais et ouvrir rapidement un autre pad si besoin.
Mais effectivement ça fait perdre des précieux pixels. Je me penche sur des alternatives.
